# Generated by Django 4.0.7 on 2023-12-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_baseuser_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='posts_count',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subscriber_count',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subscription_count',
        ),
        migrations.AddField(
            model_name='baseuser',
            name='role',
            field=models.CharField(choices=[('SL', 'Seller'), ('BY', 'Buyer')], default='user', max_length=20),
        ),
    ]
