# Generated by Django 4.0.7 on 2023-12-11 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_bio_remove_profile_posts_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='role',
        ),
    ]
